/*
 * Copyright 2016 The Cartographer Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef CARTOGRAPHER_MAPPING_POSE_GRAPH_RUNTIME_OPTIONS_H_
#define CARTOGRAPHER_MAPPING_POSE_GRAPH_RUNTIME_OPTIONS_H_

#include <string>
#include <utility>
#include <vector>

// Generated by protoc from pose_graph_options.proto (not in src/; under
// devel_isolated/cartographer/include/ after building cartographer).
// Its purpose is to enable the code to use the C++ type PoseGraphOptions
#include "cartographer/mapping/proto/pose_graph_options.pb.h"

namespace cartographer {
namespace mapping {

// Applies dotted-key overrides to 'options'. Keys are relative to POSE_GRAPH,
// e.g. "constraint_builder.min_score".
// Returns an empty string on success, otherwise an error message.
// Only options that are read at runtime (thresholds/weights/flags) are
// supported. Fast/Ceres scan matcher nested options are rejected.
std::string ApplyPoseGraphRuntimeOptions(
    const std::vector<std::pair<std::string, std::string>>& name_value_pairs,
    proto::PoseGraphOptions* options);

}  // namespace mapping
}  // namespace cartographer

#endif  // CARTOGRAPHER_MAPPING_POSE_GRAPH_RUNTIME_OPTIONS_H_
